version: '3'
services:
    nginx-rtmp-docker:
        image: nginx-rtmp-docker
        container_name: nginx-rtmp-docker
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - _APP_URL=$SERVICE_FQDN_NGINX_RTMP_DOCKER
            - SERVICE_FQDN_NGINX_RTMP_DOCKER_8888
        ports:
            - '172.22.22.108:18650:1935'
        restart: unless-stopped
        volumes:
            # - ./nginx.conf:/etc/nginx/nginx.conf
            - /var/www/hls:/var/www/hls
volumes:
    nginxcache:
